### ISSUE TITLE
Internal links should not be checked

### ISSUE THREAD

**Issue by wilhelmer** [terakilobyte/link-checker#1]
I'm using a static site generator to generate HTML output from multiple markdown files.

In the markdown files, there are internal links (from one MD file to another) and external links (starting with http:// or https://).

**Internal**
`For more information, see [this section](section2.md).`

**External**
`For more information, see [this website](https://www.mywebsite.com).`

Only the external links should be checked.

Otherwise: Great extension, thanks! 👍

**Comment by wilhelmer** [comment]
It works a lot better if you disable links that don't start with `http://` or `https://`.

To do so, replace this line:
https://github.com/terakilobyte/link-checker/blob/f8d7d31ad6c1150d68ddbd39a8d546ad6ac9ee21/src/extension.ts#L67

With:
```typescript
links = linkify.find(line).filter(link => /https?:\/\//.test(link.value));
```

**Comment by terakilobyte** [comment]
Thanks!

**Comment by terakilobyte** [comment]
This has been updated and fixed with a subsequent commit.
